#include <Bonobo.idl>

module GNOME {
	
  module Goobox {
		
    interface Application : Bonobo::Unknown {
      oneway void set_device (in string device);
      oneway void present ();
      oneway void play ();
      oneway void play_pause ();
      oneway void next ();
      oneway void prev ();
      oneway void eject ();
      oneway void hide_show ();
      oneway void volume_up ();
      oneway void volume_down ();
      oneway void quit ();
    };
    
  };
  
};
