/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define GNOME_Goobox_COMMON
#include "GNOME_Goobox.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_GNOME_Goobox
void
_ORBIT_skel_small_GNOME_Goobox_Application_present
   (POA_GNOME_Goobox_Application * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    void (*_impl_present) (PortableServer_Servant _servant,
			   CORBA_Environment * ev))
{
   _impl_present(_o_servant, _o_ev);
}

#endif
#if ( (TC_IMPL_TC_GNOME_Goobox_Application_0 == 'G') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_1 == 'N') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_2 == 'O') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_3 == 'M') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_4 == 'E') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_5 == '_') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_6 == 'G') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_7 == 'o') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_8 == 'o') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_9 == 'b') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_10 == 'o') \
&& (TC_IMPL_TC_GNOME_Goobox_Application_11 == 'x') \
) && !defined(TC_DEF_TC_GNOME_Goobox_Application)
#define TC_DEF_TC_GNOME_Goobox_Application 1
#ifdef ORBIT_IDL_C_IMODULE_GNOME_Goobox
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_Goobox_Application_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_POINTER,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "Application",
   "IDL:GNOME/Goobox/Application:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_GNOME_Goobox
CORBA_unsigned_long GNOME_Goobox_Application__classid = 0;
#endif

/* Interface type data */

#ifdef ORBIT_IDL_C_IMODULE_GNOME_Goobox
static
#endif
ORBit_IMethod GNOME_Goobox_Application__imethods[] = {
   {
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_void, "present", 7,
    0 | ORBit_I_METHOD_1_WAY}
};
static CORBA_string GNOME_Goobox_Application__base_itypes[] = {
   "IDL:Bonobo/Unknown:1.0",
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_GNOME_Goobox
static
#endif
ORBit_IInterface GNOME_Goobox_Application__iinterface = {
   TC_GNOME_Goobox_Application, {1, 1, GNOME_Goobox_Application__imethods,
				 FALSE},
   {2, 2, GNOME_Goobox_Application__base_itypes, FALSE}
};
